"""Privacy-safe, one-way shadow decision records.

This module deliberately knows nothing about FastAPI responses, route objects,
provider payloads, prompts, or model calls.  Callers build a small allow-listed
record *after* producing the rider-facing result, then submit it to a sink.
The sink cannot return a replacement decision and failures are contained.

``shadow`` means a counterfactual baseline evaluation compared with the
existing production intelligence choice.  It does not imply that baseline is
the route currently displayed to a rider.
"""

from __future__ import annotations

from dataclasses import dataclass
from datetime import UTC, datetime
from enum import Enum
import json
from pathlib import Path
import re
from typing import Any, Awaitable, Callable, Generic, Mapping, Protocol, Sequence, TypeVar
from uuid import UUID, uuid4


class EvidenceKind(str, Enum):
    """Whether the comparison came from deterministic replay or live shadow."""

    DETERMINISTIC_FIXTURE = "deterministic_fixture"
    LIVE_SHADOW = "live_shadow"


class ShadowEvaluationStatus(str, Enum):
    """Safe status codes; raw provider/model errors never enter a record."""

    COMPLETE = "complete"
    DISABLED = "disabled"
    TIMEOUT = "timeout"
    FAILED = "failed"
    FALLBACK = "fallback"
    NOT_EVALUATED = "not_evaluated"


class ReviewClassification(str, Enum):
    CORRECT_IMPROVEMENT = "correct_improvement"
    EQUIVALENT_ROUTE = "equivalent_route"
    UNNECESSARY_REROUTE = "unnecessary_reroute"
    MISSED_DISRUPTION = "missed_disruption"
    INCORRECT_INCIDENT_ASSOCIATION = "incorrect_incident_association"
    MODEL_DECISION_ERROR = "model_decision_error"
    DATA_QUALITY_ISSUE = "data_quality_issue"
    UNABLE_TO_DETERMINE = "unable_to_determine"


class SourceContribution(str, Enum):
    """Known evidence labels; arbitrary upstream strings are never persisted."""

    MTA_ALERTS = "mta_alerts"
    STALLED_SUBWAY = "stalled_subway"
    STALLED_BUS = "stalled_bus"
    GROK_X = "grok_x"
    GROK_WEB = "grok_web"
    CACHED_511NY = "cached_511ny"
    TICKETMASTER = "ticketmaster"


# Route candidate IDs are generated by the trip endpoint.  Keeping this exact
# shape prevents a caller from smuggling a request/session identifier into the
# otherwise safe comparison record.
_SAFE_CANDIDATE_ID = re.compile(r"^candidate-[0-9]{1,3}$")
_SAFE_LINE = re.compile(r"^[A-Za-z0-9]{1,8}$")
_MAX_CANDIDATES = 12
_MAX_SOURCES = len(SourceContribution)
DEFAULT_SHADOW_TIMEOUT_S = 2.0
_MAX_SHADOW_TIMEOUT_S = 30.0
_DisplayedResult = TypeVar("_DisplayedResult")


def _enum(value: object, enum_type: type[Enum], default: Enum) -> Enum:
    if isinstance(value, enum_type):
        return value
    try:
        return enum_type(str(value))  # type: ignore[call-arg]
    except (TypeError, ValueError):
        return default


def _safe_nonnegative_int(value: object, *, maximum: int = 86_400_000) -> int | None:
    if isinstance(value, bool):
        return None
    try:
        parsed = int(value)
    except (TypeError, ValueError):
        return None
    return parsed if 0 <= parsed <= maximum else None


def _safe_candidate_id(value: object) -> str | None:
    candidate_id = str(value or "").strip()
    return candidate_id if _SAFE_CANDIDATE_ID.fullmatch(candidate_id) else None


def _safe_lines(value: object) -> tuple[str, ...]:
    if not isinstance(value, (list, tuple, set)):
        return ()
    lines: list[str] = []
    for item in value:
        line = str(item or "").strip().upper()
        if _SAFE_LINE.fullmatch(line) and line not in lines:
            lines.append(line)
        if len(lines) >= 8:
            break
    return tuple(lines)


def _safe_source_counts(value: object) -> tuple[tuple[SourceContribution, int], ...]:
    if not isinstance(value, Mapping):
        return ()
    counts: list[tuple[SourceContribution, int]] = []
    for raw_source, raw_count in value.items():
        source = _enum(raw_source, SourceContribution, None)  # type: ignore[arg-type]
        count = _safe_nonnegative_int(raw_count, maximum=10_000)
        if source is not None and count is not None:
            counts.append((source, count))
    return tuple(sorted(counts, key=lambda pair: pair[0].value)[:_MAX_SOURCES])


@dataclass(frozen=True)
class CandidateDecisionSummary:
    """Small diagnostic view, intentionally without stops, geometry, or text."""

    candidate_id: str
    transit_lines: tuple[str, ...]
    scheduled_minutes: int | None
    transfers: int | None
    core_mta_score: int | None

    @classmethod
    def from_mapping(cls, raw: Mapping[str, Any]) -> "CandidateDecisionSummary | None":
        candidate_id = _safe_candidate_id(raw.get("candidate_id") or raw.get("id"))
        if candidate_id is None:
            return None
        return cls(
            candidate_id=candidate_id,
            transit_lines=_safe_lines(raw.get("transit_lines") or raw.get("lines")),
            scheduled_minutes=_safe_nonnegative_int(raw.get("scheduled_minutes") or raw.get("total_minutes"), maximum=1_440),
            transfers=_safe_nonnegative_int(raw.get("transfers"), maximum=20),
            # This is a core-MTA display diagnostic, not a model score.
            core_mta_score=_safe_nonnegative_int(raw.get("core_mta_score") or raw.get("selection_score"), maximum=10_000),
        )

    def as_dict(self) -> dict[str, Any]:
        return {
            "candidate_id": self.candidate_id,
            "transit_lines": list(self.transit_lines),
            "scheduled_minutes": self.scheduled_minutes,
            "transfers": self.transfers,
            "core_mta_score": self.core_mta_score,
        }


@dataclass(frozen=True)
class ShadowDecisionRecord:
    """Allow-listed comparison record suitable for fixture or live analysis."""

    schema_version: int
    observation_id: str
    recorded_at_iso: str
    evidence_kind: EvidenceKind
    scenario_id: str | None
    advisor_provider: str
    advisor_model: str
    production_intelligence_route_id: str | None
    production_intelligence_status: ShadowEvaluationStatus
    counterfactual_baseline_route_id: str | None
    counterfactual_baseline_status: ShadowEvaluationStatus
    route_changed: bool | None
    candidate_summaries: tuple[CandidateDecisionSummary, ...]
    source_counts: tuple[tuple[SourceContribution, int], ...]
    incident_count: int
    ticketmaster_event_count: int
    scan_status: ShadowEvaluationStatus
    ny511_snapshot_status: str
    intelligence_latency_ms: int | None
    baseline_latency_ms: int | None
    shadow_overhead_ms: int | None

    def as_dict(self) -> dict[str, Any]:
        return {
            "schema_version": self.schema_version,
            "observation_id": self.observation_id,
            "recorded_at": self.recorded_at_iso,
            "evidence_kind": self.evidence_kind.value,
            "scenario_id": self.scenario_id,
            "advisor_provider": self.advisor_provider,
            "advisor_model": self.advisor_model,
            "production_intelligence": {
                "selected_route_id": self.production_intelligence_route_id,
                "status": self.production_intelligence_status.value,
            },
            "counterfactual_baseline": {
                "selected_route_id": self.counterfactual_baseline_route_id,
                "status": self.counterfactual_baseline_status.value,
            },
            "route_changed": self.route_changed,
            "candidate_summaries": [item.as_dict() for item in self.candidate_summaries],
            "source_counts": {source.value: count for source, count in self.source_counts},
            "incident_count": self.incident_count,
            "ticketmaster_event_count": self.ticketmaster_event_count,
            "scan_status": self.scan_status.value,
            "ny511_snapshot_status": self.ny511_snapshot_status,
            "timing_ms": {
                "production_intelligence": self.intelligence_latency_ms,
                "counterfactual_baseline": self.baseline_latency_ms,
                "shadow_overhead": self.shadow_overhead_ms,
            },
        }


@dataclass(frozen=True)
class CounterfactualBaselineEvaluation:
    """The only result accepted from a bounded counterfactual evaluator."""

    selected_route_id: str | None
    status: ShadowEvaluationStatus = ShadowEvaluationStatus.COMPLETE


@dataclass(frozen=True)
class ShadowExecutionOutcome(Generic[_DisplayedResult]):
    """One-way execution result: the displayed object is always untouched."""

    displayed_result: _DisplayedResult
    baseline_status: ShadowEvaluationStatus
    baseline_latency_ms: int | None
    shadow_overhead_ms: int | None
    record: ShadowDecisionRecord | None
    submitted: bool


def _bounded_timeout(value: object) -> float:
    if isinstance(value, bool):
        return DEFAULT_SHADOW_TIMEOUT_S
    try:
        parsed = float(value)
    except (TypeError, ValueError):
        return DEFAULT_SHADOW_TIMEOUT_S
    return parsed if 0 < parsed <= _MAX_SHADOW_TIMEOUT_S else DEFAULT_SHADOW_TIMEOUT_S


def _coerce_baseline_evaluation(value: object) -> CounterfactualBaselineEvaluation:
    if isinstance(value, CounterfactualBaselineEvaluation):
        return value
    if isinstance(value, Mapping):
        return CounterfactualBaselineEvaluation(
            selected_route_id=_safe_candidate_id(value.get("selected_route_id")),
            status=_enum(value.get("status"), ShadowEvaluationStatus, ShadowEvaluationStatus.FAILED),
        )
    return CounterfactualBaselineEvaluation(None, ShadowEvaluationStatus.FAILED)


async def execute_counterfactual_shadow(
    displayed_result: _DisplayedResult,
    *,
    enabled: bool = False,
    baseline_evaluator: Callable[[], Awaitable[CounterfactualBaselineEvaluation | Mapping[str, object]]] | None = None,
    timeout_s: object = DEFAULT_SHADOW_TIMEOUT_S,
    record_factory: Callable[[CounterfactualBaselineEvaluation, int | None, int | None], ShadowDecisionRecord] | None = None,
    sink: "ShadowRecordSink | None" = None,
) -> ShadowExecutionOutcome[_DisplayedResult]:
    """Bound and contain an optional post-decision baseline evaluation.

    This deliberately receives an already-created displayed result and never
    passes it to the evaluator, sink, or record factory. Callers can run this
    after their intelligence choice is final. Disabled is the safe default;
    it makes no model/provider call and writes no record.
    """

    if not enabled or baseline_evaluator is None or record_factory is None:
        return ShadowExecutionOutcome(
            displayed_result=displayed_result,
            baseline_status=ShadowEvaluationStatus.DISABLED,
            baseline_latency_ms=None,
            shadow_overhead_ms=None,
            record=None,
            submitted=False,
        )

    import asyncio
    import time

    started = time.monotonic()
    baseline_status = ShadowEvaluationStatus.FAILED
    evaluation = CounterfactualBaselineEvaluation(None, baseline_status)
    try:
        evaluation = _coerce_baseline_evaluation(
            await asyncio.wait_for(baseline_evaluator(), timeout=_bounded_timeout(timeout_s))
        )
        baseline_status = evaluation.status
    except asyncio.TimeoutError:
        baseline_status = ShadowEvaluationStatus.TIMEOUT
        evaluation = CounterfactualBaselineEvaluation(None, baseline_status)
    except Exception:
        baseline_status = ShadowEvaluationStatus.FAILED
        evaluation = CounterfactualBaselineEvaluation(None, baseline_status)
    baseline_latency_ms = _safe_nonnegative_int(round((time.monotonic() - started) * 1000))
    overhead_ms = _safe_nonnegative_int(round((time.monotonic() - started) * 1000))
    try:
        record = record_factory(evaluation, baseline_latency_ms, overhead_ms)
    except Exception:
        return ShadowExecutionOutcome(
            displayed_result, ShadowEvaluationStatus.FAILED, baseline_latency_ms, overhead_ms, None, False
        )
    submitted = submit_shadow_record_safely(sink or NullShadowSink(), record)
    return ShadowExecutionOutcome(
        displayed_result, baseline_status, baseline_latency_ms, overhead_ms, record, submitted
    )


def build_shadow_record(
    *,
    evidence_kind: EvidenceKind | str,
    advisor_identity: Mapping[str, object],
    production_intelligence_route_id: object,
    production_intelligence_status: ShadowEvaluationStatus | str = ShadowEvaluationStatus.COMPLETE,
    counterfactual_baseline_route_id: object = None,
    counterfactual_baseline_status: ShadowEvaluationStatus | str = ShadowEvaluationStatus.NOT_EVALUATED,
    candidate_summaries: Sequence[Mapping[str, Any]] | None = None,
    source_counts: Mapping[str, object] | None = None,
    incident_count: object = 0,
    ticketmaster_event_count: object = 0,
    scan_status: ShadowEvaluationStatus | str = ShadowEvaluationStatus.NOT_EVALUATED,
    ny511_snapshot_status: object = "not_evaluated",
    intelligence_latency_ms: object = None,
    baseline_latency_ms: object = None,
    shadow_overhead_ms: object = None,
    scenario_id: object = None,
    recorded_at: datetime | None = None,
) -> ShadowDecisionRecord:
    """Build a record from scalar values only.

    There is deliberately no request/session/message/origin/destination argument.
    The observed ID is generated locally and cannot be correlated with a client
    identifier by this module.
    """

    kind = _enum(evidence_kind, EvidenceKind, EvidenceKind.LIVE_SHADOW)
    provider = str(advisor_identity.get("advisor_provider") or "unknown").strip().lower()
    model = str(advisor_identity.get("advisor_model") or "unknown").strip()
    provider = provider if re.fullmatch(r"[a-z0-9_-]{1,32}", provider) else "unknown"
    model = model if re.fullmatch(r"[A-Za-z0-9._:-]{1,120}", model) else "unknown"
    candidate_rows = tuple(
        row
        for raw in (candidate_summaries or ())[:_MAX_CANDIDATES]
        if isinstance(raw, Mapping)
        for row in (CandidateDecisionSummary.from_mapping(raw),)
        if row is not None
    )
    production_route = _safe_candidate_id(production_intelligence_route_id)
    baseline_route = _safe_candidate_id(counterfactual_baseline_route_id)
    production_status = _enum(production_intelligence_status, ShadowEvaluationStatus, ShadowEvaluationStatus.FAILED)
    baseline_status = _enum(counterfactual_baseline_status, ShadowEvaluationStatus, ShadowEvaluationStatus.FAILED)
    route_changed = (
        production_route != baseline_route
        if production_route is not None and baseline_route is not None
        and production_status in {ShadowEvaluationStatus.COMPLETE, ShadowEvaluationStatus.FALLBACK}
        and baseline_status in {ShadowEvaluationStatus.COMPLETE, ShadowEvaluationStatus.FALLBACK}
        else None
    )
    parsed_scenario = str(scenario_id or "").strip()
    if kind is EvidenceKind.LIVE_SHADOW or not re.fullmatch(r"[a-z0-9][a-z0-9_-]{0,79}", parsed_scenario):
        parsed_scenario = ""
    now = (recorded_at or datetime.now(UTC)).astimezone(UTC)
    snapshot_status = str(ny511_snapshot_status or "not_evaluated").strip().lower()
    if snapshot_status not in {"fresh", "stale", "unavailable", "disabled", "not_evaluated"}:
        snapshot_status = "unavailable"
    return ShadowDecisionRecord(
        schema_version=1,
        observation_id=str(uuid4()),
        recorded_at_iso=now.isoformat(),
        evidence_kind=kind,
        scenario_id=parsed_scenario or None,
        advisor_provider=provider,
        advisor_model=model,
        production_intelligence_route_id=production_route,
        production_intelligence_status=production_status,
        counterfactual_baseline_route_id=baseline_route,
        counterfactual_baseline_status=baseline_status,
        route_changed=route_changed,
        candidate_summaries=candidate_rows,
        source_counts=_safe_source_counts(source_counts),
        incident_count=_safe_nonnegative_int(incident_count, maximum=10_000) or 0,
        ticketmaster_event_count=_safe_nonnegative_int(ticketmaster_event_count, maximum=10_000) or 0,
        scan_status=_enum(scan_status, ShadowEvaluationStatus, ShadowEvaluationStatus.FAILED),
        ny511_snapshot_status=snapshot_status,
        intelligence_latency_ms=_safe_nonnegative_int(intelligence_latency_ms),
        baseline_latency_ms=_safe_nonnegative_int(baseline_latency_ms),
        shadow_overhead_ms=_safe_nonnegative_int(shadow_overhead_ms),
    )


class ShadowRecordSink(Protocol):
    def submit(self, record: ShadowDecisionRecord) -> None:
        """Persist a record. Implementations must not return routing data."""


class NullShadowSink:
    """Production-safe default: no persistence and no behavioral effect."""

    def submit(self, record: ShadowDecisionRecord) -> None:
        del record


class InMemoryShadowSink:
    """Test/replay sink retaining only sanitized immutable record dictionaries."""

    def __init__(self) -> None:
        self.records: list[dict[str, Any]] = []

    def submit(self, record: ShadowDecisionRecord) -> None:
        # JSON round-trip prevents callers from mutating our stored structure.
        self.records.append(json.loads(json.dumps(record.as_dict(), sort_keys=True)))


class JsonlShadowSink:
    """Explicit opt-in local sink; never configured automatically."""

    def __init__(self, path: str | Path) -> None:
        self.path = Path(path)
        if self.path.suffix.lower() != ".jsonl":
            raise ValueError("shadow record path must use a .jsonl suffix")

    def submit(self, record: ShadowDecisionRecord) -> None:
        self.path.parent.mkdir(parents=True, exist_ok=True)
        serialized = json.dumps(record.as_dict(), separators=(",", ":"), sort_keys=True)
        with self.path.open("a", encoding="utf-8", newline="\n") as output:
            output.write(serialized + "\n")


@dataclass(frozen=True)
class ShadowReview:
    """Human classification without a free-text field that can retain PII."""

    observation_id: str
    classification: ReviewClassification
    reviewed_at_iso: str

    @classmethod
    def create(
        cls,
        observation_id: object,
        classification: ReviewClassification | str,
        *,
        reviewed_at: datetime | None = None,
    ) -> "ShadowReview":
        parsed_id = str(observation_id or "").strip()
        # Observation IDs are generated UUIDv4 values by build_shadow_record.
        try:
            parsed_uuid = UUID(parsed_id)
        except (ValueError, AttributeError) as exc:
            raise ValueError("review requires a shadow observation UUID")
        if parsed_uuid.version != 4:
            raise ValueError("review requires a shadow observation UUIDv4")
        try:
            parsed_classification = (
                classification
                if isinstance(classification, ReviewClassification)
                else ReviewClassification(str(classification))
            )
        except ValueError as exc:
            raise ValueError("unknown shadow review classification") from exc
        now = (reviewed_at or datetime.now(UTC)).astimezone(UTC)
        return cls(str(parsed_uuid), parsed_classification, now.isoformat())

    def as_dict(self) -> dict[str, str]:
        return {
            "observation_id": self.observation_id,
            "classification": self.classification.value,
            "reviewed_at": self.reviewed_at_iso,
        }


class ShadowReviewStore(Protocol):
    def submit_review(self, review: ShadowReview) -> None:
        """Persist one append-only human classification."""


class JsonlShadowReviewStore:
    def __init__(self, path: str | Path) -> None:
        self.path = Path(path)
        if self.path.suffix.lower() != ".jsonl":
            raise ValueError("shadow review path must use a .jsonl suffix")

    def submit_review(self, review: ShadowReview) -> None:
        self.path.parent.mkdir(parents=True, exist_ok=True)
        with self.path.open("a", encoding="utf-8", newline="\n") as output:
            output.write(json.dumps(review.as_dict(), separators=(",", ":"), sort_keys=True) + "\n")


def submit_shadow_record_safely(sink: ShadowRecordSink, record: ShadowDecisionRecord) -> bool:
    """Contain storage failures so a log can never replace a rider decision."""

    try:
        sink.submit(record)
    except Exception:
        return False
    return True
